In [1]:
import numpy as np

In [13]:
escalar = 42
vector = np.array([10,10,10])
matriz = np.array([[2,3],[4,5],[6,7]])

In [15]:
A = vector
B = matriz
C = A + B
print(C)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [22]:
B + A.T

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [19]:
D=A +B.T
print(D)

[[12 14 16]
 [13 15 17]]


In [17]:
B + escalar

array([[44, 45],
       [46, 47],
       [48, 49]])

In [21]:
E=matriz+np.array([[42],[42],[42]])
print(E)

[[44 45]
 [46 47]
 [48 49]]
