In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector1=np.array([2,3,5,7])
matriz1=np.array([[1,2,3],[1,2,3]])
tensor1= np.array([[[255,255,255],[255,255,255],[255,255,255]],
                   [[0,0,0],[0,0,0],[0,0,0]],
                   [[128,128,128],[128,128,128],[128,128,128]],])

In [3]:
print(escalar)

5.679


In [4]:
print(vector1)

[2 3 5 7]


In [5]:
print(matriz1)

[[1 2 3]
 [1 2 3]]


In [6]:
print(tensor1)

[[[255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[128 128 128]
  [128 128 128]
  [128 128 128]]]


In [7]:
print(escalar.shape)

AttributeError: 'float' object has no attribute 'shape'

In [8]:
print(vector1.shape)

(4,)


In [9]:
vector1.shape

(4,)

In [10]:
vector1

array([2, 3, 5, 7])

In [11]:
print(vector1)

[2 3 5 7]


In [12]:
len(vector1)

4

In [13]:
matriz1.shape

(2, 3)

In [14]:
len(matriz1)

2

In [15]:
#cantidad de elementos
#dado de multiplicar dimensiones
tensor1.size

27

In [16]:
##cantidad de filas,cantidad de columnas,cantidad de matrizes
tensor1.shape

(3, 3, 3)

In [17]:
vector1.shape

(4,)

In [18]:
#cantidad de filas,cantidad de columnas
matriz1.shape

(2, 3)