In [1]:
import numpy as np

In [12]:
escalar = 5.679
vector1=np.array([2,3,5,7])
matriz1=np.array([[1,2,3],[1,2,3]])
tensor1= np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                   [[13,14,15,16],[17,18,19,20],[21,22,23,24]],
                   [[25,26,27,28],[29,30,31,32],[33,34,35,36]],])

In [3]:
escalar_t = escalar.T
print(escalar_tcalar)

AttributeError: 'float' object has no attribute 'T'

In [8]:
vector1_t=vector1.T
print(vector1_t)
print(vector1)

[2 3 5 7]
[2 3 5 7]


In [10]:
matriz1_t=matriz1.T
#matriz 3x2
print(matriz1_t)
#matriz 2x3
print(matriz1)

[[1 1]
 [2 2]
 [3 3]]
[[1 2 3]
 [1 2 3]]


In [13]:
tensor1_t=tensor1.T
print(tensor1_t)

[[[ 1 13 25]
  [ 5 17 29]
  [ 9 21 33]]

 [[ 2 14 26]
  [ 6 18 30]
  [10 22 34]]

 [[ 3 15 27]
  [ 7 19 31]
  [11 23 35]]

 [[ 4 16 28]
  [ 8 20 32]
  [12 24 36]]]


In [14]:
print(tensor1_t.T)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [16]:
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[6,5],[4,3],[2,1]])
C=A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]
