In [1]:
#Matriz identidad = Como el 1 en matematicas, el elemento neutro
#Matriz Inversa = Cumple lo siguiente: A*A^-1 = Id
#Matriz Singular = No es Matriz Inversa

import numpy as np

In [2]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
#todos los valores de la matriz estan definidos como float
vector = np.array([[2],[3],[5],[7]])
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [4]:
#Producto Interno
A = identidad.dot(vector)
print(A)

[[2.]
 [3.]
 [5.]
 [7.]]


In [5]:
#Matriz como una transformacion lineal, tengo un vector que lo transformo cuando le aplico una matriz
#Aplicar una matriz es multiplicar
#La identidad no transforma ese espacio

B = np.array([[1,0,1],[0,1,1],[-1,1,1]])
inversa_B= np.linalg.inv(B)

In [6]:
print(inversa_B)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [7]:
print(B.dot(inversa_B))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#Cuando no tiene inversa es una matriz singular

In [9]:
singular = np.array([[1,1],[1,1]])
print(singular)

[[1 1]
 [1 1]]


In [10]:
inversa_singular = np.linalg.inv(singular)

LinAlgError: Singular matrix

In [11]:
#En la clase anterior teniamos la ecuacion general A.x =b
#A.x = b no verlo asi x = b/A
#la forma correcta de obtener x es con la inversa de A y x =b.A**-1