In [1]:
import numpy as np

In [2]:
A=np.array([[2,3],[5,7],[11,13]])
B=np.array([[1,3],[2,1]])
C=np.array([[3,1],[4,2]])

In [4]:
#Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [5]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


In [6]:
#Distributiva
D = A.dot(B+C)
print(D)
E = A.dot(B) + A.dot(C)
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [7]:
#Verificar que todos son iguales
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
#Commutacion de matrices NO
F = B.dot(C)
G = C.dot(B)
print(F==G)


[[False False]
 [False False]]


In [9]:
#inspeccionemos
print(F)
print(G)

[[15  7]
 [10  4]]
[[ 5 10]
 [ 8 14]]


In [10]:
v1 = np.array([[2],[7]])
v2= np.array([[3],[5]])

In [11]:
#vector horizontalv1 y vector verticalv2
v1_tv2=v1.T.dot(v2)
v2_tv1=v2.T.dot(v1)
print(v1_tv2)
print(v2_tv1)

[[41]]
[[41]]


In [12]:
print(v1_tv2==v2_tv1)

[[ True]]
