In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [4]:
A = matriz * vector
#Producto interno
B = matriz.dot(vector)
print(A)
print(B)

[[ 2  6]
 [ 6 12]
 [10 18]]
[ 8 18 28]


In [5]:
#Hay 2 formas de llamar el producto interno
B=matriz.dot(vector)
C=np.dot(matriz,vector)
print(B,C)

[ 8 18 28] [ 8 18 28]


In [6]:
#ejercicio multiplicar un vector x una matriz y una matriz x un vector