In [23]:
import numpy as np
#configurar un decimal cuando el numero sea muy cercano a cero y tenga muchas decimales
np.set_printoptions(suppress=True)

In [26]:
A = np.array([[3,1],[2,1]])
b =np.array([[1],[1]])
A_inversa=np.linalg.inv(A)
print(A_inversa)
x = A_inversa.dot(b)
print(x)

[[ 1. -1.]
 [-2.  3.]]
[[0.]
 [1.]]


In [31]:
#Cambiamos los valores a b de [[1],[1]] a [[3],[7]]

In [28]:
#Podemos hallar la solucion
sol_2 = A_inversa.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [30]:
print(A.dot(sol_2))

[[3.]
 [7.]]
