In [10]:
#Pq un SEL tenga solucion necesitamos que
#Matriz A cuadrada, vectores linealmente independiente

In [11]:
import numpy as np

In [9]:
A = np.array(
[[0,1,0,0],
[0,0,1,0],
[0,1,1,0],
[1,0,0,1]])
#Es una matriz cuadrada pero no todos sus vectores son LIndep

In [5]:
#Como saber cual fila de la matriz es el vector LD
#Usamos los autovectores y autovalores
#AVe y AVa son una forma de descomponer la matriz

In [8]:
#.eig() manera de buscar los autovalores y autovectores
lambdas, V= np.linalg.eig(A.T)
print(A[lambdas == 0,:])
#obtenemos un LD
#Podemos decir que es una matriz singular pq tiene un LD dentro de sus filas

[[0 1 1 0]]


In [12]:
#xq Si sumamos el v1 y el v2 obtenemos el v3
'''
matematicamente pasa lo siguiente:
para calcular la matriz inversa se calcula primero la transpuesta de la matriz adjunta y esta se divide por el determinante de la matriz.

Cuando en una matriz tenemos vectores LD tantos en columnas como en filas el determinante es 0, SIEMPRE haciendo que la division no se pueda resolver

'''

'\nmatematicamente pasa lo siguiente:\npara calcular la matriz inversa se calcula primero la transpuesta de la matriz adjunta y esta se divide por el determinante de la matriz.\n\nCuando en una matriz tenemos vectores LD tantos en columnas como en filas el determinante es 0, SIEMPRE haciendo que la division no se pueda resolver\n\n'

In [13]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [15]:
z = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9,10, 11,12]])
m = z.T
print(m)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
A= np.array([[7,-1],[3,-1]])

In [19]:
b= np.array([-2,-5])

A_inv=np.linalg.inv(A)
x=b.dot(A_inv)
print(x)

[-4.25  9.25]
