In [1]:
import numpy as np

In [3]:
#Matriz de identidad tiene una diagonal de 1 es el elemento neutro
#Matriz inversa
#Matriz Singular
vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)
print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
#Otro tipo de matriz que son diagonales pero no son cuadradas
print(matriz[0:4,0:3])
#4filas-3columnas

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [5]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [8]:
#vertical
v1 = np.array([[1,1,1,1]])
#horizontal
v1 = np.array([1,1,1,1])
print(A.dot(v1.T))

[[2]
 [3]
 [4]
 [5]]


In [9]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [11]:
identidad= A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
A_inv_calc= np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [14]:
#Matriz Simetrica A = A**t Matriz = Matriz.T

In [ ]:
'''
(AB)_T = A_T * B_T
pero si A = B
entonces
(AB)_T = A * B
Tiene implicaciones muy importantes porque simplifica las operaciones que
estamos realizando.
'''