In [1]:
'''
Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales
y todas sus columnas son mutuamente ortonormales'''


'\nUna matriz es ortogonal cuando todas sus filas son mutuamente ortonormales\ny todas sus columnas son mutuamente ortonormales'

In [2]:
import numpy as np


In [4]:
matriz = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
# : 2puntos indica una columna 0->primera 1-> segunda
print(matriz[:,0].dot(matriz[:,1]))

0


In [7]:
#v1 es ortogonal a v2
#v1 es ortogonal a v3
#v2 es ortogonal a v3

In [8]:
print(matriz[:,0])

[1 0 0]


In [17]:
print('FILAS')
print(matriz[:,0].dot(matriz[:,1]))

FILAS
0


In [11]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [19]:
print(matriz[:,1].dot(matriz[:,2]))

0


In [16]:
print('COLUMAS')
print(matriz[0,:].dot(matriz[1,:]))

COLUMAS
0


In [14]:
print(matriz[0,:].dot(matriz[2,:]))

0


In [15]:
print(matriz[1,:].dot(matriz[2,:]))

0


In [21]:
#Comprobar si las filas son Ortonormales
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [22]:
#Comprobar si las columnas son Ortonormales
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [24]:
#Propiedad de Matriz Ortogonal
# A**t.A = A.A**t = Identidad
#entonces
# A**t = A**-1(inversa)  Porque deshace las operaciones de A

In [27]:
#Veamos una forma sencilla de generar matrices ortogonales.
A = np.array([[np.cos(100),-np.sin(100)],
            [np.sin(100),np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [29]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))


0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [30]:
#problemas computacionales para representar los numeros
#Debio salir 1 

In [31]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [32]:
A_t = A.T
print(A_t.dot(A))
print(A.dot(A_t))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [33]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [36]:
print(1/A.dot(A_t))

[[ 1. inf]
 [inf  1.]]


<ipython-input-36-b6490d573f8c>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(1/A.dot(A_t))


In [ ]:
'''El profesor nunca menciona por que elige la matriz con seno y coseno. Resulta que esa matriz, se llama una “matriz de rotación”. La cual me permite rotar un vector 90 grados. Es por esta razón que es una matriz ortogonal.'''
